CREATE TABLE `coupon` (
  `id` bigint(20) NOT NULL COMMENT 'ä¼˜æƒ åˆ¸æ¨¡æ¿ID',
  `coupon_name` varchar(50) DEFAULT NULL COMMENT '优惠券模板名称',
  `brand_id` bigint(11) DEFAULT NULL COMMENT '品牌ID ',
  `coupon_type` tinyint(4) DEFAULT NULL COMMENT '优惠券模板类别(1:满减券, 2:折扣券, 3:礼品券, 4:现金券)',
  `image` bigint(20) DEFAULT NULL COMMENT '优惠券图片',
  `image_old` bigint(20) DEFAULT NULL COMMENT '优惠券原图，即未加水印的图片',
  `instructions` varchar(1000) DEFAULT NULL COMMENT '优惠券的详情描述',
  `full_value` int(10) DEFAULT NULL COMMENT '满额可用',
  `rule_desc` varchar(256) DEFAULT NULL COMMENT '优惠券使用规则描述',
  `memo` varchar(1000) DEFAULT NULL,
  `use_scene` tinyint(4) DEFAULT NULL COMMENT '使用场景，0:全部 ; 1:堂食; 2:外卖',
  `status` tinyint(4) DEFAULT '0' COMMENT '状态(0:启用, 1:停用)',
  `creator_id` bigint(20) DEFAULT NULL COMMENT '创建人',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater_id` bigint(20) DEFAULT NULL COMMENT '修改人',
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `is_delete` tinyint(4) DEFAULT NULL COMMENT '是否删除(0 否; -1 是)',
  `week` varchar(7) NOT NULL DEFAULT '1111111' COMMENT '星期（七位字符串表示，1表示可用，0表示不可用，第一位表示周日，最后一位表示周六。如1100000表示周日、周一可用。1111110表示除了周六都能用）',
  `create_type` tinyint(4) DEFAULT '1' COMMENT '1：老优惠券模板，2：新优惠券模板',
  `apply_dish` tinyint(4) DEFAULT '1' COMMENT '适用商品：1, 全部商品;2, 部分商品;3,部分商品不可用，礼品券没有适用商品',
  PRIMARY KEY (`id`),
  KEY `idx_coupon_brand_id` (`brand_id`) USING BTREE,
  KEY `idx_coupon_update_time` (`update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='优惠券信息模板';